Make test workflow configurable
ottofeller/templates pull request #225
Opened 2023-03-29 15:13 UTC by quesabe

Closes PLA-202.

2023-03-29 15:43 UTC, gvidon commented on src/common/github/pull-request-test-workflow.ts
> +   * or within the project parent (for subprojects).
@quesabe is the parent project passed through the `project` input param?

2023-03-29 15:44 UTC, gvidon requested changes
@quesabe would that be hard to introduce test cases for this functionality? We need to be sure that nested projects can add their workflows to the parent project's `.github/` dir.

2023-03-31 05:29 UTC, quesabe commented
> @quesabe would that be hard to introduce test cases for this functionality? We need to be sure that nested projects can add their workflows to the parent project's `.github/` dir.

Not a problem. I should have done it in the first place.

2023-04-02 19:04 UTC, gvidon commented on src/common/github/pull-request-test-workflow.ts
> +   * `hasDefaultGithubWorkflows` option disables workflow creation making the method a simple noop.
@quesabe not really happy with the noop part and would prefer the method having no such logic, but let’s keep it like this for now.

2023-04-02 19:13 UTC, gvidon approved these changes

2023-04-02 19:13 UTC, merged